LOCAL_PATH := $(my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := RkExplorer.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
include $(BUILD_PREBUILT)

